/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlycosovatchat;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ADMIN
 */
public class Cosovatchat extends javax.swing.JFrame {

   
    
    quanlycosovatchatmodel model;
    vatchatdao daoVC = new vatchatdao();
    
    public Cosovatchat() {
        this.model = new quanlycosovatchatmodel();
        initComponents();
        System.out.println("Ngay mai se khac");
System.out.println("Ngay mai se khac");
System.out.println("Ngay mai se khac");
System.out.println("Ngay mai se khac");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bntthem = new javax.swing.JButton();
        bntxoa = new javax.swing.JButton();
        bntlammoi = new javax.swing.JButton();
        bnttimkiem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmavatchat = new javax.swing.JTextField();
        txttenvatchat = new javax.swing.JTextField();
        txtsoluongnhap = new javax.swing.JTextField();
        txtsoluongcon = new javax.swing.JTextField();
        txtphongbansudung = new javax.swing.JTextField();
        txtsoluongdasudung = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbvatchat = new javax.swing.JTable();
        bntthoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 0, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycosovatchat/icon/iconsset2/nha.jpg"))); // NOI18N
        jLabel1.setText("QUẢN LÝ CƠ SỞ VẬT CHẤT");

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin cơ sở vật chất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 16), new java.awt.Color(255, 0, 51))); // NOI18N

        bntthem.setBackground(new java.awt.Color(255, 51, 51));
        bntthem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bntthem.setForeground(new java.awt.Color(255, 255, 255));
        bntthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycosovatchat/icon/iconsset2/Actions-document-edit-icon-16.png"))); // NOI18N
        bntthem.setText("Thêm");
        bntthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntthemActionPerformed(evt);
            }
        });

        bntxoa.setBackground(new java.awt.Color(255, 0, 51));
        bntxoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bntxoa.setForeground(new java.awt.Color(255, 255, 255));
        bntxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycosovatchat/icon/iconsset2/Actions-edit-delete-icon-16.png"))); // NOI18N
        bntxoa.setText("Xóa");
        bntxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntxoaActionPerformed(evt);
            }
        });

        bntlammoi.setBackground(new java.awt.Color(255, 0, 51));
        bntlammoi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bntlammoi.setForeground(new java.awt.Color(255, 255, 255));
        bntlammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycosovatchat/icon/iconsset2/new-icon-16.png"))); // NOI18N
        bntlammoi.setText("Làm mới");
        bntlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntlammoiActionPerformed(evt);
            }
        });

        bnttimkiem.setBackground(new java.awt.Color(255, 51, 51));
        bnttimkiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bnttimkiem.setForeground(new java.awt.Color(255, 255, 255));
        bnttimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycosovatchat/icon/iconsset2/search-icon-24.png"))); // NOI18N
        bnttimkiem.setText("Tìm kiếm");
        bnttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnttimkiemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã Vật Chất:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên vật chất:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Số Lượng Nhập:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số Lượng Còn:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phòng ban sử dụng:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Số lượng đã sử dụng: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtsoluongnhap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttenvatchat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmavatchat, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsoluongcon, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsoluongdasudung, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtphongbansudung, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(bnttimkiem)
                        .addGap(62, 62, 62)
                        .addComponent(bntlammoi)
                        .addGap(59, 59, 59)
                        .addComponent(bntxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(bntthem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmavatchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtsoluongdasudung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttenvatchat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtphongbansudung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bnttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntthem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsoluongnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsoluongcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31))))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách cơ sở vật chất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        tbvatchat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã vật chất", "Tên vật chất", "Số lượng nhập", "Số lượng còn", "Phòng ban sử dụng", "Số lượng đã sử dụng"
            }
        ));
        jScrollPane1.setViewportView(tbvatchat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        bntthoat.setBackground(new java.awt.Color(255, 0, 51));
        bntthoat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bntthoat.setForeground(new java.awt.Color(255, 255, 255));
        bntthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycosovatchat/icon/iconsset2/logout-icon-16.png"))); // NOI18N
        bntthoat.setText("Thoát");
        bntthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bntthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void showDuLieu(){
        try{
            tbvatchat.removeAll();
            String[] arr = {"Mã Vật Chất", "Tên vật chất", "Số lượng nhập", "Số Lượng Còn","Số lượng đã sử dụng", "Phòng ban đã sử dụng"};
            DefaultTableModel model = new DefaultTableModel(arr,0);
            tbvatchat.setModel(model);
            Connection connection = DBConnection.getConnection();
            String query = "SELECT *FROM dbo.[quanlycosovatchat]";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                Vector vector = new Vector();
                vector.add(rs.getString("idVatChat"));
                vector.add(rs.getString("TenVatChat"));
                vector.add(rs.getString("SoLuongNhap"));
                vector.add(rs.getString("SoLuongCon"));
                vector.add(rs.getString("Soluongdasudung"));
                vector.add(rs.getString("PhongBanSuDung"));
                
                model.addRow(vector);

            }
            //đóng kết nối 
            DBConnection.closeConnection(connection);
            tbvatchat.setModel((TableModel) model);
        }catch(SQLException ex){
           Logger.getLogger(Cosovatchat.class.getName()).log(Level.SEVERE,null,ex);
           
        }
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        showDuLieu();
    }//GEN-LAST:event_formComponentShown

    private void bntthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bntthoatActionPerformed

    private void bntxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntxoaActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn xóa không");
        if(result == 0 ){
            int position = tbvatchat.getSelectedRow();
            String data = tbvatchat.getModel().getValueAt(position, 0).toString();
              try{
                Connection connection = DBConnection.getConnection();
                String query = "DELETE FROM dbo.[quanlycosovatchat] WHERE idVatChat = ? ";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setString(1,data);
                ps.executeUpdate();
                showDuLieu();
                DBConnection.closeConnection(connection);
                JOptionPane.showMessageDialog(null,"Xóa thành công");
        
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }                    
    }//GEN-LAST:event_bntxoaActionPerformed
    
    
     public void resetForm(){
        txtmavatchat.setText("");
        txttenvatchat.setText("");
        //cboquequan.setSelectedIndex(0);
        txtsoluongnhap.setText("");
        txtsoluongcon.setText("");
        txtsoluongdasudung.setText("");
        txtphongbansudung.setText("");
       
    }
    
    private void bntlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntlammoiActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_bntlammoiActionPerformed

    
    //Trùng mã vật chất
    private boolean checkTrungMVC(){
        try{
            Connection connection = DBConnection.getConnection();
            String query = "SELECT *FROM dbo.[quanlycosovatchat] WHERE idVatChat = ?";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1,txtmavatchat.getText());
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
               return true;
            }
            //đóng kết nối 
            DBConnection.closeConnection(connection);
            tbvatchat.setModel((TableModel) model);
        }catch(SQLException ex){
           Logger.getLogger(Cosovatchat.class.getName()).log(Level.SEVERE,null,ex);
           
        }
        return false;
    }
    
    private void bntthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntthemActionPerformed
        // TODO add your handling code here:
        if(txtmavatchat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Mã vật chất không được rỗng");
            txtmavatchat.requestFocus();
            return;
        }else if(txttenvatchat.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tên vật chất không được rỗng");
            txttenvatchat.requestFocus();
            return;
        }else if(txtsoluongnhap.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Số lượng không được rỗng");
            txtsoluongnhap.requestFocus();
            return;
        }else if(txtsoluongcon.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Số lượng còn không được rỗng");
            txtsoluongcon.requestFocus();
            return;
        } else if(txtsoluongdasudung.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Số lượng đã sử dụng không được rỗng");
            txtsoluongdasudung.requestFocus();
            return;
        }else if(txtphongbansudung.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Phòng ban su dung không được rỗng");
            txtphongbansudung.requestFocus();
            return;
        }
        
        //trùng mã vật chất
        
        if(checkTrungMVC() == true){
            JOptionPane.showMessageDialog(null,"Mã vật chất này đã tồn tại");
            txtmavatchat.requestFocus();
            return;
        }else{
            try{
            Connection connection = DBConnection.getConnection();
            String query = "INSERT INTO dbo.quanlycosovatchat(idVatChat, TenVatChat, SoLuongNhap, SoLuongCon, SoLuongDaSuDung, PhongBanSuDung)"
                        + "VALUES(?,?,?,?,?,?)";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1,txtmavatchat.getText());
            ps.setString(2,txttenvatchat.getText());
            ps.setString(3,txtsoluongnhap.getText());
            ps.setString(4,txtsoluongcon.getText());
            ps.setString(5,txtsoluongdasudung.getText());
            ps.setString(6,txtphongbansudung.getText());
            ps.executeUpdate();
            showDuLieu();
            DBConnection.closeConnection(connection);
            JOptionPane.showMessageDialog(null,"Thêm thành công");
        
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        }    
        
    }//GEN-LAST:event_bntthemActionPerformed

     public vatchat findvatchatByMVC(String maVatChat){
        Iterable<vatchat> slVC = null;
        for(vatchat vc : slVC){
            if(vc.getIdVatChat().equalsIgnoreCase(maVatChat)){
                return vc;
            }
        }
        return null;
        
    }
    
    
    private void bnttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnttimkiemActionPerformed
        // TODO add your handling code here:
        vatchat tsFind = daoVC.findvatchatByMVC(txtmavatchat.getText());
        if(tsFind != null){
            setModel(tsFind);
        }else{
            JOptionPane.showMessageDialog(null,"Không tìm thấy");

        }
        
    }//GEN-LAST:event_bnttimkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cosovatchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cosovatchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cosovatchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cosovatchat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cosovatchat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntlammoi;
    private javax.swing.JButton bntthem;
    private javax.swing.JButton bntthoat;
    private javax.swing.JButton bnttimkiem;
    private javax.swing.JButton bntxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbvatchat;
    private javax.swing.JTextField txtmavatchat;
    private javax.swing.JTextField txtphongbansudung;
    private javax.swing.JTextField txtsoluongcon;
    private javax.swing.JTextField txtsoluongdasudung;
    private javax.swing.JTextField txtsoluongnhap;
    private javax.swing.JTextField txttenvatchat;
    // End of variables declaration//GEN-END:variables

    private void setModel(vatchat tsFind) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
